### ISSUE TITLE
Scripts (PowerShell) - Not Displaying Script Content

### ISSUE THREAD

**Issue by edtrax** [Micke-K/IntuneManagement#100]
When adding the scriptContent column, there is no data in said column. I am expecting to see at the very least the guid or script ID. But there is no data at all.

**Comment by Micke-K** [comment]
Hello!

I assume this is about PowerShell scripts.

This is by design. Script content is kind of a "lazy" property so it is not populated when all objects are downloaded from Graph. It is only available when a single object is retrieved. So to follow best practice and minimizing calls to MS Graph, the property will not be populated and therefore empty when the column is added. It is also stored as a base64 string so the content  would not be in readable format.

Check the details view of a script object. The scriptContent property is not populated until you click the "Load full" button. 

Cheers!

**Comment by edtrax** [comment]
Thank you!

-Eddie
________________________________
