### ISSUE TITLE
Scope Tags are not being assigned.

### ISSUE THREAD

**Issue by Odnel** [Micke-K/IntuneManagement#133]
Hello!

I've recently started testing your script and I am loving it!

I've encountered strange issue when using import option.

I've tried to import a compliance policies, but each policy does not have assigned scope tag.

I am using Assign Scope (tag) option, all of the Scope Tags are present in the environment before import is done.

Logs are showing below error:
![image](https://user-images.githubusercontent.com/33906109/236248590-440d454a-7dc1-4e59-80da-a7b4b151b412.png)

My assumption was lack of privileges, but app has DeviceManagementRBAC.ReadWrite.All assigned.

It seems to be similar to issue #61 , but it seems there issue was lack of Scope Tags in the tenant, which is not the case here.

Any help will be appreciated :)

**Comment by Micke-K** [comment]
Hello!

Did you export the ScopeTags? Is there a folder for them in the exported folder?

You have to export dependency objects. The script will use that during import so it can eg translate a scope tag. This is required because objects will not have the same id in different environments. The dependency objects must be imported first. A full batch import will take care of that but must be done manually if importing single objects/object types. 

Cheers!

**Comment by Odnel** [comment]
Hello!

Yes, the ScopeTags were exported and they are present in the folder.

As the ScopeTags are already in the tenant I am using option "Skip if object exists" when importing the settings and I can see that ScopeTags are being read by the script (and skipped, due to being in tenant already). ScopeTags are being imported as one of the first objects.

Can this option make a difference in importing dependency objects?

For now I am testing this script on the same tenant so ScopeTags that were exported are exactly the same as in the .json files that were exported.

**Comment by Micke-K** [comment]
Hello,

I'm trying to figure this one out. The image from the log makes no sense to me since that means it can't find a menu item for ScopeTags. 

I did find some weirdness when importing into the same tenant. 

Can you try the attached file and try again. Just replace the existing MSGraph.psm1. 

If this is not working, can you attach a full log?

Cheers!

[MSGraph.zip](https://github.com/Micke-K/IntuneManagement/files/11421578/MSGraph.zip)

**Comment by Odnel** [comment]
Apologies for a late response. Attached file worked as expected. Thank you!
