### ISSUE TITLE
Import application fails

### ISSUE THREAD

**Issue by Frank-GTH** [Micke-K/IntuneManagement#180]
In the release 3.9.4 I cannot import an exported (and modified) Win32 application anymore. This used to work upto this release.

**Comment by Micke-K** [comment]
Hello,

Do you have log? There was no change in the import for apps. There was a change in upload a few versions back. I'll have a look and see if there's a change that could have had an impact on apps. 

Do they import without content or not import at all?

Cheers!

**Comment by Frank-GTH** [comment]
Hi,

They do not import at all, with or without Intunewin file. No error displayed.

Regards, Frank

**Comment by Micke-K** [comment]
Hello,

Not sure if you closed this because you got it to work or not. If not you could just open it again. 

I did some tests this morning and I had no problem importing an app. 

If you still have an issue then what kind of app are you importing, anything in the log file (no errors will be displayed in the UI)

Cheers and Merry Christmas

**Comment by Frank-GTH** [comment]
Did not mean to close it, sorry. I am importing a Win32 app with a very small data file. Ik will test again next week and look at the logs.

**Comment by Micke-K** [comment]
Thank you for testing and verifying.

Chers!
