### ISSUE TITLE
All "SettingsCatalog" Policies don´t recognize their assignments

### ISSUE THREAD

**Issue by mathias1202** [Micke-K/IntuneManagement#187]
Hi, 

I import our whole set of policies and everything works fine.
But when I check the policies that where in the SettingsCatalog folder, all of them don´t recognize their assignment.

Do you know, what causes this? 

![image](https://github.com/Micke-K/IntuneManagement/assets/55585150/3a408b5c-686f-4830-bcba-3399ae3154b0)

![image](https://github.com/Micke-K/IntuneManagement/assets/55585150/e3dffb42-e0b3-46a3-96bc-c58ec71b754b)

**Comment by Micke-K** [comment]
Hello,

I'm trying to understand the screen shots. 

- What profile type are you looking at? Settings Catalog is used in Device Configuration and many of the Endpoint Security policies.
- What's Selected groups? I'm expecting to see a group name there.
- Error retrieving data - Is that one of the issues?
- Were groups created during import or manually created?
- Any dynamic / synced groups? That can cause issues. Dynamic group should be able to be migrated but synced groups will be converted to cloud group.
- Just to understand the question. What is the exact issue have? Assignments missing, groups not created, filters not added, the filter options are not available, error retrieving data from groups or something else? 

I did some test moving between environment with groups missing, added during import, policies with/without filters etc.

- Importing without groups - No assignment created -> As expected
- Importing with groups and assignments but filters not available in export folder -> Imported with assignments but filters not assigned -> As expected.
- Importing with groups and assignments with filter available in export folder -> Imported with assignments and filters assigned -> As expected.

Cheers!

**Comment by Micke-K** [comment]
Hello,

I ran into this today and now I know a bit more what you meant.

"Selected groups" means that the group does not exists eg deleted. This used to be just an empty string. Error retrieving data is caused by it is trying to receive members from a deleted group so that is expected.

Not sure if you imported assignments with groupId for a group that doesn't exist (is that even possible?) or the group for these policies was actually deleted after import. If it was during import, the tool "should have created" the group but that depends if exported group info was available during import.

Cheers!

**Comment by mathias1202** [comment]
It was a layer 8 problem - me :) 

In the last weeks I tested various things and it seems that I confused some policies from one test with policies from another test. So like you said in your last comment, I imported policies that were assigned to groups from another tenant.

Thanks!
