### ISSUE TITLE
Documentation feature does respect changed item delimeter

### ISSUE THREAD

**Issue by SasStu** [Micke-K/IntuneManagement#20]
Changing the item delimiter in the CSV documentation dialogue is not respected in the output it still uses commas.

**Comment by Micke-K** [comment]
Do you mean that the CSV uses commas as delimiter? If that is the case then it is by design. The property and object separators are for the values. Example: The property separator is for each column of a firewall rule (port, protocol etc.) and object separator for each FW rule you have configured. There is no support for changing CSV delimiter at the moment.
Or are you saying that the value is not using the correct property\object separator?

**Comment by SasStu** [comment]
Thank you for the quick reply. I understood that the delimeter is used in the CSV file as well. It would be a nice feature though because some of the item descriptions (e.g. iOS Device Restrictions) are containing commas which makes it more difficult to use the CSV in Excel for example.

**Comment by Micke-K** [comment]
I've started this already. It will be included in the next release.
