### ISSUE TITLE
File upload fails during application import

### ISSUE THREAD

**Issue by danielvgoodsuite** [Micke-K/IntuneManagement#218]
The application import process appears to work, but the file upload is failing. Please see attached screenshot.

![image](https://github.com/Micke-K/IntuneManagement/assets/75397614/40a86ae0-7e44-4d2d-91fd-628cf7debeb8)

**Comment by Micke-K** [comment]
Hello,

I could not replicate the issue.

Is the intunewin file valid? Can you rename it to zip and open it? What version of PowerShell are you using?

Can you try the attached file and see if that makes any difference?

This happens when I do a test import of an app.

![image](https://github.com/Micke-K/IntuneManagement/assets/43226266/bc896cf0-9ab5-4257-8193-b3060f551f79)

Cheers!

[IntuneAppManagement.zip](https://github.com/Micke-K/IntuneManagement/files/15130104/IntuneAppManagement.zip)

**Comment by danielvgoodsuite** [comment]
Yes, the intunewin file is valid and has been used multiple times successfully. I was using PowerShell 7.4.2 when the error occurred. I tested again with PowerShell 5.1 and it worked without issue. Thank you for looking into this for me.
