### ISSUE TITLE
Your app is not ready yet. Check back again soon

### ISSUE THREAD

**Issue by trmpluym** [Micke-K/IntuneManagement#22]
When exporting and importing Windows apps the app is created but the app cannot we used. The message is: 'Your app is not ready yet. Check back again soon'. When i look at the export folder the MSI file is missing. 

For example: i created an 7-Zip app. The export is a 7-Jip.json file. In the 7-Jip.json file there is a line:  "fileName":  "7z1900-x64.msi".
But the required msi file is missing.

**Comment by Micke-K** [comment]
The tool will not export the application files. It can't do that because the files are encrypted and the deception keys are not available. 

If you have the original files you can store them in a folder and specify the path in Settings. The script will the upload the file. 

I asked Microsoft two years ago if they could make the decryption keys available but it hasn't happened yet

**Comment by trmpluym** [comment]
Hi Micke,

Thanks for you quick response !
It is a pity Microsoft does not release the decryption keys.
But I have the original MSI’s available and found the folder setting.
It works like a charm !
Thank you for making this great tool !

Theo

**Comment by Micke-K** [comment]
That is great!

Thank you for using the tool.
