### ISSUE TITLE
Viewing Endpoint Security Microsoft Defender Antivirus Policy breaks after logging in with Intune Manager

### ISSUE THREAD

**Issue by MaximLibant** [Micke-K/IntuneManagement#236]
## Issue summary
After logging in and consenting to API permissions for Intune Manager, viewing Antivirus policies in the Intune web portal stops working for specifically for policies matching the following criteria:
    - platform: "Windows 10, Windows 11, and Windows Server" 
    - profile type: "Microsoft Defender Antivirus" 
    
Intune Manager version: 3.9.6
powershell version: 7.4.2

 ## Expected behaviour
After logging into the endpoint manager web portal, I should be able to navigate to *Endpoint Security > Antivirus* and view. create. or modify a new or existing policy settings for:
    - platform: "Windows 10, Windows 11, and Windows Server" 
    - profile type: "Microsoft Defender Antivirus"
    
 ## Issue
When attempting to load / view the configuration settings for the policy, the web portal will start to throw an error. Editing the name, scope or assignments all function. Only the profile configuration cannot be viewed. Below is an example of an error provided by Intune. 

This has happened to me on 2 different tenants after logging in with Intune Manager. The issue did not exist prior to using Intune Manager

[Screenshot of issue](https://i.imgur.com/rH30P43.png)

`{"error":{"code":"InternalServerError","message":"{\r\n  \"_version\": 3,\r\n  \"Message\": \"An internal server error has occurred - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: d963564a-375c-48e1-9d6d-bf8165ccfe65 - Url: https://fef.msua08.manage.microsoft.com/DeviceConfigV2/DCV2GraphService/de147310-ffff-9717-0512-061220203495/deviceManagement/configurationPolicyTemplates('804339ad-1553-4478-a742-138fb5807418_1')/settingTemplates?api-version=5024-04-01&$expand=settingDefinitions&$top=1000\",\r\n  \"CustomApiErrorPhrase\": \"\",\r\n  \"RetryAfter\": null,\r\n  \"ErrorSourceService\": \"\",\r\n  \"HttpHeaders\": \"{}\"\r\n}","innerError":{"date":"2024-06-15T02:59:51","request-id":"854b7f8e-49e9-4ea6-8a6e-4e63200b4427","client-request-id":"d963564a-375c-48e1-9d6d-bf8165ccfe65"}}}`

## Replication
- Log into Intune on a tenant with a valid license
    - my first tenant only has business premium licenses
    - second tenant has a mix of f3, business premium, e3 and e5 licenses
- Verify web portal functionality by creating a new policy:
    - platform: "Windows 10, Windows 11, and Windows Server" 
    - profile type: "Microsoft Defender Antivirus"
- Set a name, attempt to view & modify configuration settings. If the settings load then functionality is working as expected.
- Optionally save the profile
- Log into Intune Manager 3.9.6, accept and consent to required API permissions. 
- Go back to Intune web portal
- You will now no longer be able to view or modify the policy settings
- You also won't be able to create any new polices for the same platform & profile type

## Troubleshooting I've done
- Verify the issue doesn't happen on a tenant where Intune Manager has not been used.
- Export / import a profile from a working tenant using the web interface
- Export / import a profile from a working tenant using Intune manager
- Remove API Permisisons
- Re-grant API pmerisisons
- Verify Admin consent
- Using the graph API explorer I am still able to get a response using "https://graph.microsoft.com/beta/deviceManagement/configurationPolicyTemplates/<policy_id>/settingTemplates"

This could be something that will resolve on it's own, or I may have to reach out to MS support to get this resolved but I figured I'd open an issue here as well just in case. It's only been ~8 hours since first encountering this issue.

**Comment by Micke-K** [comment]
Hello,

This is a weird one. I've done some initial tests now in two environments. I cannot replicate it. Both environments were created this year and I tested with latest version of IntuneManager.

The consent in the IntuneManger (latest version) would consent the Enterprise App 'Microsoft Graph Command Line Tools' with App ID '14d82eec-204b-4c2f-b7e8-296a70dab67e'. Same App as used by the MS Graph PowerShell module. I found it really weird how enabling this app could break something in the web portal. 

What happens if you enable this app and give consent via the Graph PowerShell module? And what happens if you remove the 'Microsoft Graph Command Line Tools' Enterprise App - Be very careful with this in case others uses it. 

I removed the ''Microsoft Graph Command Line Tools'' app and re-did the consent in IntuneManager. I could still not re-produce the error. The Defender Antivirus policy is still there in the portal, and I can edit it without any errors. I can still create more policies. I followed the instructions above.

I also copied a policy from one environment to another but still no error.

I did notice that these are Settings Catalog policies, and they use their own query to list them:

/deviceManagement/configurationPolicies?$filter=(technologies eq 'configManager' and creationSource eq 'SccmAV' or creationSource eq 'WindowsSecurity')
 
This would only return "Windows 10, Windows 11, and Windows Server" policies. Not sure if this is new eg migrated from Intent to Settings Catalog and that is why it fails to load. Another thing I found weird with these policies is that the templateReference is empty. A template is normally used for Endpoint Security policies that are Settings Catalog. But then again, these use the creationSource that I don't think I've seen used elsewhere. 

I don't have any old export of these policies so I can't say if they changed this now or if it was long time ago. 

I can't see how an app registration for Graph CLI would break a policy type in the portal.  I can see that importing a policy with missing settings could generate the error. This could happen if an imported policy has extra settings or missing settings, and the code Microsoft uses to display the UI then crashes. Or if Microsoft currently are doing some changes in the background of these policies that causes the UI to break. I have seen that before...

Are the policies listed in Intune Manager (Settings Catalog)? It would be interesting to see an export of the policy when it is working and then compare it with one that is not working. There must be something different. 

Cheers!

**Comment by MaximLibant** [comment]
Update: 

I checked back on the weekend but the issue was still occurring. I tried to revoke / renew / regrant permissions through the app and Powershell. Neither had any effect. 

I unfortunately don't have any good exports to share, but on the bright side, I checked back this morning and the policies are working on both tenants again. Very strange. 

I agree that it wouldn't make sense for consenting to an enterprise app to mess with Intune web portal functionality. So for now I'll call it strange coincidence.
