### ISSUE TITLE
When importing win32 app(with no content or encryption keys,just export and then import) app stays "locked"

### ISSUE THREAD

**Issue by Mbenz-byte** [Micke-K/IntuneManagement#276]
Hi
When importing win32 app that was exported from different tenant(with no content or encryption keys, just export and then import) app stays "locked"
so doesn't let you edit or do anything with it and says:
"Your app is not ready yet. If app content is uploading, wait for it to finish. If app content is not uploading, try creating the app again."

anyway around it? i don't care uploading file again later but there is no way to do that.
i think i might have the originals somewhere but not sure i have them for all apps so i wonder if there is away to just created them so they are editable?

 Thanks in advance

**Comment by Micke-K** [comment]
Hello,

This is expected behaviour since Intune will block any application changes until the file is uploaded. You can upload the file manually later in the tool. Go to the app and select View. You have an option to upload it from there. Intune does not have that option. Once the file is uploaded, you will be able to edit the file in Intune again.

Cheers!

**Comment by Mbenz-byte** [comment]
Thanks
Yes, I figure d that out so great and thanks for this great tool it really is a time saver.
