### ISSUE TITLE
Security Baseline - controls in export and UI do not match

### ISSUE THREAD

**Issue by jonwbstr** [Micke-K/IntuneManagement#3]
This is a list of controls I found in the UI, that are not in the json export of the security baseline

Control | Category | Description
-- | -- | --
PreventSmartScreenPromptOverride | Browser | Block malicious site   access
PreventSmartScreenPromptOverrideForFiles | Browser | Block unverified file download
BehaviorOfTheElevationPromptForAdministrators | Local Policies Security Options | Administrator elevation prompt behavior
OnlyElevateUIAccessApplicationsThatAreInstalledInSecureLocations | Local Policies   Security Options | Allow UI access applications for secure   locations
PreventOverrideForFilesInShell | Smart Screen | Block execution of unverified files

These are controls I found in the json export, that I was unable to associate with a control exposed by the azure intune UI.

DefinitionId | Category | Description
-- | -- | --
deviceConfiguration--windows10GeneralConfiguration_smartScreenBlockPromptOverride | Browser | ??
deviceConfiguration--windows10GeneralConfiguration_smartScreenBlockPromptOverrideForFiles | Browser | ??

**Comment by Micke-K** [comment]
Very long delay on this answer but I've check this now based on a documented policy.
The controls exists in the export except for the 'Block execution of unverified files' which is probably removed because I can't find it in the UI either.


Control | Definition ID
-- | -- 
Block malicious site access | deviceConfiguration--windows10GeneralConfiguration_smartScreenBlockPromptOverride
Block unverified file download | deviceConfiguration--windows10GeneralConfiguration_smartScreenBlockPromptOverrideForFiles
Administrator elevation prompt behavior | deviceConfiguration--windows10EndpointProtectionConfiguration_localSecurityOptionsAdministratorElevationPromptBehavior
Allow UI access applications for secure locations | deviceConfiguration--windows10EndpointProtectionConfiguration_localSecurityOptionsAllowUIAccessApplicationsForSecureLocations
