### ISSUE TITLE
Feature request: Select columns

### ISSUE THREAD

**Issue by Phoenix-DH** [Micke-K/IntuneManagement#30]
Hey,

as already mentioned, I started to love this tool.
Makes administrating a big environment much more comfortable.

What I am asking is if it is possible to give the possibility to select columns/info?

Thanks for a reply.

Greetz Dominik

**Comment by Micke-K** [comment]
Hello!

Thank for using the tool. 

This is an interesting request. This will require some re-developing. I've actually thought about this earlier and skipped the idea, but since you brought it up as a request, I'll have a look at it. 

I've been super busy lately so not sure when I can do this. Might not be included in the next update since it will most likely require more than a minor update. 

Thank you!

**Comment by Phoenix-DH** [comment]
Don't hurry! Would be nice to have.

**Comment by Micke-K** [comment]
3.2.3 released with limited supported for this. Limited in the sense that you have to manually add reg values for additional columns. Please see the README file for complete instructions on how to use custom columns. 
 
I know it's not the optimal solution but it is a start. Try it out a let me know what you think. I hope I can get the time to add support for it in the UI in the future.

**Comment by Phoenix-DH** [comment]
Will take a look! Thank you for the fast pre implementation.

**Comment by Micke-K** [comment]
Yes, UI for selecting columns would be good. I hope I can get time to add that.

Assignments are not included in the list return. It is possible with $the expand parameter like when loading the full object. What are you after? If it is assigned like in the portal or group names. The names would be quite hard and probably require a scripted return for each object.

**Comment by Phoenix-DH** [comment]
I know that names are hard, ID of the AAD group will also suit. Only that you can see if something is assigned.

**Comment by Phoenix-DH** [comment]
Hey, any News on this?

**Comment by Micke-K** [comment]
Hello!

Sorry, I am overseas at the moment so a bit slow to respond. 

This is not forgotten but I am trying to figure out how to do this the best way. I haven't cone up with a good way yet that doesn't require a huge amount developing. I'll be back in Australia on the weekend so might be able to look at it from next week. There are a lot of other requests as well I gave to look at. 

Cheers and Happy New Year!

**Comment by Micke-K** [comment]
Hello!

I added support for this in the UI. Try it out when you have time and let me know what you think. 

Cheers!

**Comment by Phoenix-DH** [comment]
Hey @Micke-K,

I had a look.
Do you mean in general the possibilit to add columns to the GUI or my dedicated additional request to add input from additional GRPAH requests?

I tried to add:
1,lastModifiedDateTime=lastModifiedDateTime,version=version,assignments[0].id=id

But I did not get it managed.

**Comment by Micke-K** [comment]
Hello!

I thought it was the UI part you wanted :)

assignments[0].id=id will not work. since assignments is a sub-property and not included in the list. It could be included by including it in the Querylist string. If I remember correctly, it can't be used on some object types. I just tested this on Device Configuration and that worked

You can try that by adding &expand=assignments to the end of the string on row 107 in EndpointManager.psm1

QUERYLIST = "`$filter=not%20isof(%27microsoft.graph.windowsUpdateForBusinessConfiguration%27)%20and%20not%20isof(%27microsoft.graph.iosUpdateConfiguration%27)**&expand=assignments**"

Cheers!

**Comment by Phoenix-DH** [comment]
Damn! It works.
I got now the first assignment .... I think this will be enough to see if something is assigned or not.

Thank you.

But one additional question:
Means we have to adapt this afte each new rollout of a new version, right?
Or can you implenment it in a different way?
Maybe as additional paramter in some settings file?

**Comment by Micke-K** [comment]
I have to figure out a way to do this in a good way. I'll probably add a setting for it :)

Cheers!

**Comment by Micke-K** [comment]
3.5.0 has support for this but must be enabled 'Expand assignments' in Settings

**Comment by Phoenix-DH** [comment]
Will try ....

**Comment by Micke-K** [comment]
Closing this. This should be working now. 

Let me know if there are any issues. 

Cheers!
