### ISSUE TITLE
Markdown output

### ISSUE THREAD

**Issue by martincaddick** [Micke-K/IntuneManagement#35]
Output in word looks awesome but with Word not installed on the jumpbox I'm limited to csv. Have you considered markdown output?

**Comment by Micke-K** [comment]
Hello!

Thank you for the feature request. I have thought about this but not looked into it yet. 

I'll have a look at the md documentation and see what I need to do. I'm hoping it won't be too hard to implement. 

I'll try to get this included in the next update. I've been crazy busy lately so I haven't had much time to add new things. 

Cheers!

**Comment by martincaddick** [comment]
Happy to work thru it with you. I've been doing a bit with markdown recently. btw, when I get the prompt telling me that the CA policies do not have the correct permissions, how do I configure things to use an app registration for the CA policies?

**Comment by Micke-K** [comment]
Untick the "Use Default Permissions" in Settings. This will automatically do a grant request for missing permissions. You might have to restart it once you changed the setting. 

That is another fix on my list, grant request for missing permissions if default permissions are used.

**Comment by martincaddick** [comment]
Awesome thanks.

**Comment by Micke-K** [comment]
I had a quick look at markdown. I can now document with md as output and it looks great...until I document the whole environment. Some profile values breaks the document and in a large environment the md file gets too big to load. So I have to rethink it, maybe split the md and have one index file and one md file for each object.

**Comment by martincaddick** [comment]
I've got a couple of demo tenants and a big prod tenant if you want assistance in testing

**Comment by Micke-K** [comment]
[Documentation.psm1.txt](https://github.com/Micke-K/IntuneManagement/files/7575927/Documentation.psm1.txt)
[DocumentationMD.psm1.txt](https://github.com/Micke-K/IntuneManagement/files/7575928/DocumentationMD.psm1.txt)

Remove .txt from these files and copy them to the Extensions folder. Select Markdown when you document.

This is an experimental version of the MD documentation. It looks ok and it creates one MD file in the Documents folder. There's no support for settings etc for the moment. I'll add that if we get this to work properly. I've tested it with the Markdown Viewer add-in in Chrome. Typora did not work because it could not handle the tables being HTML. I had to do that because I needed to put code blocks in columns eg for ADMX XML data etc. It takes a long time to open the document in Chrome when I generated all my Device Configuration profiles. Not sure if it would even open if I documented all profiles.

Have a try and let me know what you think. Anything you want to change? Will it even work with one document or should it always split? What do you use for MD viewer?

I've not had the time to look at documenting exported profiles yet.

Cheers!

**Comment by Micke-K** [comment]
Hello

Official support for MD was added in 3.8.1

Let me now if you test it or if we can now close this issue

Cheers!

**Comment by Micke-K** [comment]
Hello,

Closing this issue since it is now fully supported.

Please create a new issue if you have any problems with it.

Cheers!
