### ISSUE TITLE
Conditional Access permissions missing | Microsoft Intune PowerShell

### ISSUE THREAD

**Issue by RasmusFNielsen** [Micke-K/IntuneManagement#43]
Hi,

It seems like when connecting to new tenants, the Microsoft Intune PowerShell Enterprise Application doesn't get the following permissions.:
- Policy.Read.All
- Policy.ReadWrite.ConditionalAccess
- Application.Read.All
- Organization.ReadWrite.All

**Comment by Micke-K** [comment]
Hello!

This is by design. The default behaviour changed a few versions back. The tool uses default permissions as the default settings. This is because there are environments where you as a consultant might not have permission to approve consent or request permissions and just have to accept that you don't have access to everything.

You can untick the **Use default permission** option in Setting. This will then build a consent request for all the permissions required by the tool.

I might look into adding a Consent request in the menu when default permission in used.

Cheers!
