### ISSUE TITLE
No difference in Install / Uninstall when documenting applications

### ISSUE THREAD

**Issue by worangeb** [Micke-K/IntuneManagement#98]
First of all, excellent job making this application!

When I exported the applications in the Assignments table it is not possible to see the diffence between Install or Uninstall, it's all in one table. However, in RAW mode it is visible, see example below.

# Assignments

"GroupMode","Group","Filter","FilterMode","Category","SubCategory","RawIntent"
"Included","App-XYZ","None","None","Required",,"required"
"Included","All users","None","None","Uninstall",,"uninstall"

**Comment by Micke-K** [comment]
Hello!

Thank you!

I assume you are talking about the documentation feature here or do you mean something else?

I have a ton of documentation issues to fix. I am actually rewriting parts of it at the moment. I'll see if I can add this into that change. 

Cheers!

**Comment by worangeb** [comment]
Yes, I'm talking about the documentation feature in 'Intune Manager'.
Thanks for taking you time. I just can manage it by hand right now, take it easy.

**Comment by Micke-K** [comment]
This _should_ be an easy one. If it is, I might try to add it to the bug fix release I am wrapping up at the moment. 

If you're that picky, you probably have lots of other things to report :) I know there are lots of these small things and there are lots of templates I have no clue if they are working or not. I'm very happy that someone reports issues regarding the documentation feature. That means it's being used. Please report any other issues you run into.  

Cheers!

**Comment by worangeb** [comment]
Haha, I'm just starting to use your tool 😅 It looks great already!

**Comment by Micke-K** [comment]
Hello!

Try the DocumentationWord.psm1 in the attached file. This will add intent to the documentation of Win32 apps and also all the other properties of Win32 assignments. This was by design (a bad/lazy one though). I had to redesign how the table inside a cell was rendered.

It is not 100% yet. One property has a value it shouldn't have. The final fix will come in next full update with all the other documentation fixes. I just need time to finalize them.

Let me know how it goes.

Cheers!

[Extensions.zip](https://github.com/Micke-K/IntuneManagement/files/9980915/Extensions.zip)

**Comment by Micke-K** [comment]
Hello

Fixed included in 3.8.1

Let me know if there is anything else on this or if I can close the issue

Cheers!

**Comment by worangeb** [comment]
Thanks for you update and work Micke-K!
